stages:
  - build
  - deploy

image: ${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/dev/vnfs-collector:CI-2024-08-15

variables:
  DOCKER_REGISTRY: ${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com
  IMAGE_NAME: ${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/dev/vnfs-collector:${CI_PIPELINE_ID}


build_vnfs_collector:
  stage: build
  script: |
    set -x
    python3 -m pip install .[test]
    python3 -m pytest tests/
    LATEST=${DOCKER_REGISTRY}/dev/vnfs-collector:latest
    make docker_build
    docker tag vnfs-collector ${IMAGE_NAME}
    docker tag vnfs-collector ${LATEST}
    docker push ${IMAGE_NAME}
    docker push ${LATEST}
    echo "pushed ${IMAGE_NAME}"
  tags:
    - vast-dev-builder


update_dockerhub:
  stage: deploy
  script: |
    set -x
    VERSION=$(cat version.txt)
    echo "$DOCKERHUB_PW" | docker login --username "$DOCKERHUB_USER" --password-stdin
    export IMAGE_NAME=docker.io/vastdataorg/vnfs-collector:${VERSION}
    make deb
    docker buildx create --name builder --use
    docker buildx build -f docker/debian.Dockerfile \
      --build-arg=VERSION="$VERSION" \
      --platform "linux/amd64,linux/arm64" \
      -t ${IMAGE_NAME} \
      --push .
  when: manual
  tags:
    - vast-dev-builder
