stages:
  - build

image: ${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/dev/vnfs-collector:CI-2024-08-15

variables:
  DOCKER_REGISTRY: ${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com
  IMAGE_NAME: ${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/dev/vnfs-collector:${CI_PIPELINE_ID}


build_vnfs_collector:
  stage: build
  script: |
    set -x
    LATEST=${DOCKER_REGISTRY}/dev/vnfs-collector:latest
    make docker_build
    docker tag vnfs-collector ${IMAGE_NAME}
    docker tag vnfs-collector ${LATEST}
    docker push ${IMAGE_NAME}
    docker push ${LATEST}
    echo "pushed ${IMAGE_NAME}"
  tags:
    - vast-dev-builder
