apiVersion: v1
kind: Service
metadata:
  name: vnfs-collector-service
spec:
  selector:
    app: vnfs-collector
  ports:
    - name: exporter
      protocol: TCP
      port: 9000
      targetPort: 9000
  clusterIP: None
