apiVersion: v1
kind: Service
metadata:
  name: vnfs-collector-service
spec:
  selector:
    app: vnfs-collector
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30900
  type: NodePort
