#!/bin/bash
set -e

if [ $1 == "remove" ]; then
	SERVICE_NAME="vnfs-collector"
	# Stop the systemd service if it's running
	if systemctl is-active --quiet "${SERVICE_NAME}"; then
	    systemctl stop "${SERVICE_NAME}"
	fi

	# Disable the systemd service
	systemctl disable "${SERVICE_NAME}" 2>/dev/null || true

	/opt/vnfs-collector/src/hack/pack_uninstall.sh
fi
