{
 "title": "NFS Client Metrics",
 "tags": [ "NFS-CLIENT" ],
 "time": { "from": "2024-11-17T10:00:00.000Z", "to": "2024-11-17T13:00:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "jobid",
    "label": "Select JOBID",
    "query": {
     "query": "label_values(vnfs_ACCESS_COUNT,JOBID)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Top 10 JOBIDs by Read + Write OPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, sum(vnfs_READ_COUNT) by (JOBID) + sum(vnfs_WRITE_COUNT) by (JOBID))",
     "legendFormat": "{{JOBID}}"
    }
   ]
  },
  {
   "title": "Top 10 JOBIDs by Metadata OPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, sum(vnfs_OPEN_COUNT + vnfs_CLOSE_COUNT + vnfs_GETATTR_COUNT + vnfs_SETATTR_COUNT + vnfs_READDIR_COUNT + vnfs_CREATE_COUNT + vnfs_LINK_COUNT + vnfs_UNLINK_COUNT + vnfs_SYMLINK_COUNT + vnfs_LOOKUP_COUNT + vnfs_RENAME_COUNT + vnfs_ACCESS_COUNT + vnfs_LISTXATTR_COUNT + vnfs_MKDIR_COUNT + vnfs_RMDIR_COUNT + vnfs_FLUSH_COUNT + vnfs_FSYNC_COUNT + vnfs_LOCK_COUNT + vnfs_MMAP_COUNT) by (JOBID))",
     "legendFormat": "{{JOBID}}"
    }
   ]
  },
  {
   "title": "Top 10 JOBIDs by Read + Write BW",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(10, (sum(vnfs_READ_COUNT) by (JOBID) / sum(vnfs_READ_DURATION) by (JOBID)) + (sum(vnfs_WRITE_COUNT) by (JOBID) / sum(vnfs_WRITE_DURATION) by (JOBID)))",
     "legendFormat": "{{JOBID}}"
    }
   ]
  },
  {
   "title": "Per JOBID Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read BW per JOBID",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(vnfs_READ_BYTES{JOBID=~\"$jobid\"}) by(JOBID) / sum(vnfs_READ_DURATION{JOBID=~\"$jobid\"}) by(JOBID) ",
       "legendFormat": "{{JOBID}} - Read"
      }
     ]
    },
    {
     "title": "Write BW per JOBID",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(vnfs_READ_BYTES{JOBID=~\"$jobid\"}) by(JOBID) / sum(vnfs_READ_DURATION{JOBID=~\"$jobid\"}) by(JOBID) ",
       "legendFormat": "{{JOBID}} - Read"
      }
     ]
    },
    {
     "title": "READ OPS per JOBID",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum(vnfs_READ_COUNT{JOBID=~\"$jobid\"}) by (JOBID)",
       "legendFormat": "{{JOBID}} - Read"
      }
     ]
    },
    {
     "title": "WRITE OPS per JOBID",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "sum(vnfs_WRITE_COUNT{JOBID=~\"$jobid\"}) by (JOBID)",
       "legendFormat": "{{JOBID}} - Write"
      }
     ]
    },
    {
     "title": "Read Metadata OPS per JOBID",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sum(vnfs_GETATTR_COUNT{JOBID=~\"$jobid\"} + vnfs_READDIR_COUNT{JOBID=~\"$jobid\"} + vnfs_LOOKUP_COUNT{JOBID=~\"$jobid\"} + vnfs_ACCESS_COUNT{JOBID=~\"$jobid\"} + vnfs_LISTXATTR_COUNT{JOBID=~\"$jobid\"} + vnfs_MMAP_COUNT{JOBID=~\"$jobid\"}) by (JOBID)",
       "legendFormat": "{{JOBID}}"
      }
     ]
    },
    {
     "title": "Write Metadata OPS per JOBID",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "sum(vnfs_OPEN_COUNT{JOBID=~\"$jobid\"} + vnfs_CLOSE_COUNT{JOBID=~\"$jobid\"} + vnfs_SETATTR_COUNT{JOBID=~\"$jobid\"} + vnfs_CREATE_COUNT{JOBID=~\"$jobid\"} + vnfs_LINK_COUNT{JOBID=~\"$jobid\"} + vnfs_UNLINK_COUNT{JOBID=~\"$jobid\"} + vnfs_SYMLINK_COUNT{JOBID=~\"$jobid\"} + vnfs_RENAME_COUNT{JOBID=~\"$jobid\"} + vnfs_MKDIR_COUNT{JOBID=~\"$jobid\"} + vnfs_RMDIR_COUNT{JOBID=~\"$jobid\"} + vnfs_FLUSH_COUNT{JOBID=~\"$jobid\"} + vnfs_FSYNC_COUNT{JOBID=~\"$jobid\"} + vnfs_LOCK_COUNT{JOBID=~\"$jobid\"} + vnfs_MMAP_COUNT{JOBID=~\"$jobid\"}) by (JOBID)",
       "legendFormat": "{{JOBID}}"
      }
     ]
    },
    {
     "title": "Metadata OPS Distribution per JOBID",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "sum(vnfs_OPEN_COUNT{JOBID=~\"$jobid\"}) by (JOBID)",
       "legendFormat": "{{JOBID}} - Open"
      },
      {
       "expr": "sum(vnfs_CLOSE_COUNT{JOBID=~\"$jobid\"}) by (JOBID)",
       "legendFormat": "{{JOBID}} - Close"
      },
      {
       "expr": "sum(vnfs_GETATTR_COUNT{JOBID=~\"$jobid\"}) by (JOBID)",
       "legendFormat": "{{JOBID}} - Getattr"
      },
      {
       "expr": "sum(vnfs_SETATTR_COUNT{JOBID=~\"$jobid\"}) by (JOBID)",
       "legendFormat": "{{JOBID}} - Setattr"
      },
      {
       "expr": "sum(vnfs_READDIR_COUNT{JOBID=~\"$jobid\"}) by (JOBID)",
       "legendFormat": "{{JOBID}} - Readdir"
      },
      {
       "expr": "sum(vnfs_CREATE_COUNT{JOBID=~\"$jobid\"}) by (JOBID)",
       "legendFormat": "{{JOBID}} - Create"
      },
      {
       "expr": "sum(vnfs_LINK_COUNT{JOBID=~\"$jobid\"}) by (JOBID)",
       "legendFormat": "{{JOBID}} - Link"
      },
      {
       "expr": "sum(vnfs_UNLINK_COUNT{JOBID=~\"$jobid\"}) by (JOBID)",
       "legendFormat": "{{JOBID}} - Unlink"
      },
      {
       "expr": "sum(vnfs_SYMLINK_COUNT{JOBID=~\"$jobid\"}) by (JOBID)",
       "legendFormat": "{{JOBID}} - Symlink"
      },
      {
       "expr": "sum(vnfs_LOOKUP_COUNT{JOBID=~\"$jobid\"}) by (JOBID)",
       "legendFormat": "{{JOBID}} - Lookup"
      },
      {
       "expr": "sum(vnfs_RENAME_COUNT{JOBID=~\"$jobid\"}) by (JOBID)",
       "legendFormat": "{{JOBID}} - Rename"
      },
      {
       "expr": "sum(vnfs_ACCESS_COUNT{JOBID=~\"$jobid\"}) by (JOBID)",
       "legendFormat": "{{JOBID}} - Access"
      },
      {
       "expr": "sum(vnfs_LISTXATTR_COUNT{JOBID=~\"$jobid\"}) by (JOBID)",
       "legendFormat": "{{JOBID}} - Listxattr"
      },
      {
       "expr": "sum(vnfs_MKDIR_COUNT{JOBID=~\"$jobid\"}) by (JOBID)",
       "legendFormat": "{{JOBID}} - Mkdir"
      },
      {
       "expr": "sum(vnfs_RMDIR_COUNT{JOBID=~\"$jobid\"}) by (JOBID)",
       "legendFormat": "{{JOBID}} - Rmdir"
      },
      {
       "expr": "sum(vnfs_FLUSH_COUNT{JOBID=~\"$jobid\"}) by (JOBID)",
       "legendFormat": "{{JOBID}} - Flush"
      },
      {
       "expr": "sum(vnfs_FSYNC_COUNT{JOBID=~\"$jobid\"}) by (JOBID)",
       "legendFormat": "{{JOBID}} - Fsync"
      },
      {
       "expr": "sum(vnfs_LOCK_COUNT{JOBID=~\"$jobid\"}) by (JOBID)",
       "legendFormat": "{{JOBID}} - Lock"
      },
      {
       "expr": "sum(vnfs_MMAP_COUNT{JOBID=~\"$jobid\"}) by (JOBID)",
       "legendFormat": "{{JOBID}} - Mmap"
      }
     ]
    }
   ]
  },
  { "title": "Per Mount Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Read BW per Mount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(vnfs_READ_BYTES{JOBID=~\"$jobid\"}) by(MOUNT) / sum(vnfs_READ_DURATION{JOBID=~\"$jobid\"}) by(MOUNT)",
     "legendFormat": "{{JOBID}}, {{MOUNT}}"
    }
   ]
  },
  {
   "title": "Write BW per Mount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(vnfs_WRITE_BYTES{JOBID=~\"$jobid\"}) by(MOUNT) / sum(vnfs_WRITE_DURATION{JOBID=~\"$jobid\"}) by(MOUNT)",
     "legendFormat": "{{JOBID}}, {{MOUNT}}"
    }
   ]
  },
  {
   "title": "READ OPS per Mount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(vnfs_READ_COUNT{JOBID=~\"$jobid\"}) by (MOUNT)",
     "legendFormat": "{{JOBID}}, {{MOUNT}}"
    }
   ]
  },
  {
   "title": "WRITE OPS per Mount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(vnfs_WRITE_COUNT{JOBID=~\"$jobid\"}) by (MOUNT)",
     "legendFormat": "{{JOBID}}, {{MOUNT}}"
    }
   ]
  },
  {
   "title": "Read Metadata OPS per Mount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(vnfs_GETATTR_COUNT{JOBID=~\"$jobid\"} + vnfs_READDIR_COUNT{JOBID=~\"$jobid\"} + vnfs_LOOKUP_COUNT{JOBID=~\"$jobid\"} + vnfs_ACCESS_COUNT{JOBID=~\"$jobid\"} + vnfs_LISTXATTR_COUNT{JOBID=~\"$jobid\"} + vnfs_MMAP_COUNT{JOBID=~\"$jobid\"}) by (MOUNT)",
     "legendFormat": "{{JOBID}}, {{MOUNT}}"
    }
   ]
  },
  {
   "title": "Write Metadata OPS per Mount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(vnfs_OPEN_COUNT{JOBID=~\"$jobid\"} + vnfs_CLOSE_COUNT{JOBID=~\"$jobid\"} + vnfs_SETATTR_COUNT{JOBID=~\"$jobid\"} + vnfs_CREATE_COUNT{JOBID=~\"$jobid\"} + vnfs_LINK_COUNT{JOBID=~\"$jobid\"} + vnfs_UNLINK_COUNT{JOBID=~\"$jobid\"} + vnfs_SYMLINK_COUNT{JOBID=~\"$jobid\"} + vnfs_RENAME_COUNT{JOBID=~\"$jobid\"} + vnfs_MKDIR_COUNT{JOBID=~\"$jobid\"} + vnfs_RMDIR_COUNT{JOBID=~\"$jobid\"} + vnfs_FLUSH_COUNT{JOBID=~\"$jobid\"} + vnfs_FSYNC_COUNT{JOBID=~\"$jobid\"} + vnfs_LOCK_COUNT{JOBID=~\"$jobid\"} + vnfs_MMAP_COUNT{JOBID=~\"$jobid\"}) by (MOUNT)",
     "legendFormat": "{{JOBID}}, {{MOUNT}}"
    }
   ]
  },
  {
   "title": "Metadata OPS Distribution per Mount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(vnfs_OPEN_COUNT{JOBID=~\"$jobid\"}) by (MOUNT)",
     "legendFormat": "{{MOUNT}} - Open"
    },
    {
     "expr": "sum(vnfs_CLOSE_COUNT{JOBID=~\"$jobid\"}) by (MOUNT)",
     "legendFormat": "{{MOUNT}} - Close"
    },
    {
     "expr": "sum(vnfs_GETATTR_COUNT{JOBID=~\"$jobid\"}) by (MOUNT)",
     "legendFormat": "{{MOUNT}} - Getattr"
    },
    {
     "expr": "sum(vnfs_SETATTR_COUNT{JOBID=~\"$jobid\"}) by (MOUNT)",
     "legendFormat": "{{MOUNT}} - Setattr"
    },
    {
     "expr": "sum(vnfs_READDIR_COUNT{JOBID=~\"$jobid\"}) by (MOUNT)",
     "legendFormat": "{{MOUNT}} - Readdir"
    },
    {
     "expr": "sum(vnfs_CREATE_COUNT{JOBID=~\"$jobid\"}) by (MOUNT)",
     "legendFormat": "{{MOUNT}} - Create"
    },
    {
     "expr": "sum(vnfs_LINK_COUNT{JOBID=~\"$jobid\"}) by (MOUNT)",
     "legendFormat": "{{MOUNT}} - Link"
    },
    {
     "expr": "sum(vnfs_UNLINK_COUNT{JOBID=~\"$jobid\"}) by (MOUNT)",
     "legendFormat": "{{MOUNT}} - Unlink"
    },
    {
     "expr": "sum(vnfs_SYMLINK_COUNT{JOBID=~\"$jobid\"}) by (MOUNT)",
     "legendFormat": "{{MOUNT}} - Symlink"
    },
    {
     "expr": "sum(vnfs_LOOKUP_COUNT{JOBID=~\"$jobid\"}) by (MOUNT)",
     "legendFormat": "{{MOUNT}} - Lookup"
    },
    {
     "expr": "sum(vnfs_RENAME_COUNT{JOBID=~\"$jobid\"}) by (MOUNT)",
     "legendFormat": "{{MOUNT}} - Rename"
    },
    {
     "expr": "sum(vnfs_ACCESS_COUNT{JOBID=~\"$jobid\"}) by (MOUNT)",
     "legendFormat": "{{MOUNT}} - Access"
    },
    {
     "expr": "sum(vnfs_LISTXATTR_COUNT{JOBID=~\"$jobid\"}) by (MOUNT)",
     "legendFormat": "{{MOUNT}} - Listxattr"
    },
    {
     "expr": "sum(vnfs_MKDIR_COUNT{JOBID=~\"$jobid\"}) by (MOUNT)",
     "legendFormat": "{{MOUNT}} - Mkdir"
    },
    {
     "expr": "sum(vnfs_RMDIR_COUNT{JOBID=~\"$jobid\"}) by (MOUNT)",
     "legendFormat": "{{MOUNT}} - Rmdir"
    },
    {
     "expr": "sum(vnfs_FLUSH_COUNT{JOBID=~\"$jobid\"}) by (MOUNT)",
     "legendFormat": "{{MOUNT}} - Flush"
    },
    {
     "expr": "sum(vnfs_FSYNC_COUNT{JOBID=~\"$jobid\"}) by (MOUNT)",
     "legendFormat": "{{MOUNT}} - Fsync"
    },
    {
     "expr": "sum(vnfs_LOCK_COUNT{JOBID=~\"$jobid\"}) by (MOUNT)",
     "legendFormat": "{{MOUNT}} - Lock"
    },
    {
     "expr": "sum(vnfs_MMAP_COUNT{JOBID=~\"$jobid\"}) by (MOUNT)",
     "legendFormat": "{{MOUNT}} - Mmap"
    }
   ]
  },
  { "title": "Per Remote Path Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Read BW per Remote Path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(vnfs_READ_BYTES{JOBID=~\"$jobid\"}) by(REMOTE_PATH) / sum(vnfs_READ_DURATION{JOBID=~\"$jobid\"}) by(REMOTE_PATH)",
     "legendFormat": "{{JOBID}}, {{REMOTE_PATH}}"
    }
   ]
  },
  {
   "title": "Write BW per Remote Path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(vnfs_WRITE_BYTES{JOBID=~\"$jobid\"}) by(REMOTE_PATH) / sum(vnfs_WRITE_DURATION{JOBID=~\"$jobid\"}) by(REMOTE_PATH)",
     "legendFormat": "{{JOBID}}, {{REMOTE_PATH}}"
    }
   ]
  },
  {
   "title": "READ OPS per Remote Path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum(vnfs_READ_COUNT{JOBID=~\"$jobid\"}) by (REMOTE_PATH)",
     "legendFormat": "{{JOBID}}, {{REMOTE_PATH}}"
    }
   ]
  },
  {
   "title": "WRITE OPS per Remote Path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "sum(vnfs_WRITE_COUNT{JOBID=~\"$jobid\"}) by (REMOTE_PATH)",
     "legendFormat": "{{JOBID}}, {{REMOTE_PATH}}"
    }
   ]
  },
  {
   "title": "Read Metadata OPS per Remote Path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum(vnfs_GETATTR_COUNT{JOBID=~\"$jobid\"} + vnfs_READDIR_COUNT{JOBID=~\"$jobid\"} + vnfs_LOOKUP_COUNT{JOBID=~\"$jobid\"} + vnfs_ACCESS_COUNT{JOBID=~\"$jobid\"} + vnfs_LISTXATTR_COUNT{JOBID=~\"$jobid\"} + vnfs_MMAP_COUNT{JOBID=~\"$jobid\"}) by (REMOTE_PATH)",
     "legendFormat": "{{JOBID}}, {{REMOTE_PATH}}"
    }
   ]
  },
  {
   "title": "Write Metadata OPS per Remote Path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "sum(vnfs_OPEN_COUNT{JOBID=~\"$jobid\"} + vnfs_CLOSE_COUNT{JOBID=~\"$jobid\"} + vnfs_SETATTR_COUNT{JOBID=~\"$jobid\"} + vnfs_CREATE_COUNT{JOBID=~\"$jobid\"} + vnfs_LINK_COUNT{JOBID=~\"$jobid\"} + vnfs_UNLINK_COUNT{JOBID=~\"$jobid\"} + vnfs_SYMLINK_COUNT{JOBID=~\"$jobid\"} + vnfs_RENAME_COUNT{JOBID=~\"$jobid\"} + vnfs_MKDIR_COUNT{JOBID=~\"$jobid\"} + vnfs_RMDIR_COUNT{JOBID=~\"$jobid\"} + vnfs_FLUSH_COUNT{JOBID=~\"$jobid\"} + vnfs_FSYNC_COUNT{JOBID=~\"$jobid\"} + vnfs_LOCK_COUNT{JOBID=~\"$jobid\"} + vnfs_MMAP_COUNT{JOBID=~\"$jobid\"}) by (REMOTE_PATH)",
     "legendFormat": "{{JOBID}}, {{REMOTE_PATH}}"
    }
   ]
  },
  {
   "title": "Metadata OPS Distribution per Remote Path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "sum(vnfs_OPEN_COUNT{JOBID=~\"$jobid\"}) by (REMOTE_PATH)",
     "legendFormat": "{{REMOTE_PATH}} - Open"
    },
    {
     "expr": "sum(vnfs_CLOSE_COUNT{JOBID=~\"$jobid\"}) by (REMOTE_PATH)",
     "legendFormat": "{{REMOTE_PATH}} - Close"
    },
    {
     "expr": "sum(vnfs_GETATTR_COUNT{JOBID=~\"$jobid\"}) by (REMOTE_PATH)",
     "legendFormat": "{{REMOTE_PATH}} - Getattr"
    },
    {
     "expr": "sum(vnfs_SETATTR_COUNT{JOBID=~\"$jobid\"}) by (REMOTE_PATH)",
     "legendFormat": "{{REMOTE_PATH}} - Setattr"
    },
    {
     "expr": "sum(vnfs_READDIR_COUNT{JOBID=~\"$jobid\"}) by (REMOTE_PATH)",
     "legendFormat": "{{REMOTE_PATH}} - Readdir"
    },
    {
     "expr": "sum(vnfs_CREATE_COUNT{JOBID=~\"$jobid\"}) by (REMOTE_PATH)",
     "legendFormat": "{{REMOTE_PATH}} - Create"
    },
    {
     "expr": "sum(vnfs_LINK_COUNT{JOBID=~\"$jobid\"}) by (REMOTE_PATH)",
     "legendFormat": "{{REMOTE_PATH}} - Link"
    },
    {
     "expr": "sum(vnfs_UNLINK_COUNT{JOBID=~\"$jobid\"}) by (REMOTE_PATH)",
     "legendFormat": "{{REMOTE_PATH}} - Unlink"
    },
    {
     "expr": "sum(vnfs_SYMLINK_COUNT{JOBID=~\"$jobid\"}) by (REMOTE_PATH)",
     "legendFormat": "{{REMOTE_PATH}} - Symlink"
    },
    {
     "expr": "sum(vnfs_LOOKUP_COUNT{JOBID=~\"$jobid\"}) by (REMOTE_PATH)",
     "legendFormat": "{{REMOTE_PATH}} - Lookup"
    },
    {
     "expr": "sum(vnfs_RENAME_COUNT{JOBID=~\"$jobid\"}) by (REMOTE_PATH)",
     "legendFormat": "{{REMOTE_PATH}} - Rename"
    },
    {
     "expr": "sum(vnfs_ACCESS_COUNT{JOBID=~\"$jobid\"}) by (REMOTE_PATH)",
     "legendFormat": "{{REMOTE_PATH}} - Access"
    },
    {
     "expr": "sum(vnfs_LISTXATTR_COUNT{JOBID=~\"$jobid\"}) by (REMOTE_PATH)",
     "legendFormat": "{{REMOTE_PATH}} - Listxattr"
    },
    {
     "expr": "sum(vnfs_MKDIR_COUNT{JOBID=~\"$jobid\"}) by (REMOTE_PATH)",
     "legendFormat": "{{REMOTE_PATH}} - Mkdir"
    },
    {
     "expr": "sum(vnfs_RMDIR_COUNT{JOBID=~\"$jobid\"}) by (REMOTE_PATH)",
     "legendFormat": "{{REMOTE_PATH}} - Rmdir"
    },
    {
     "expr": "sum(vnfs_FLUSH_COUNT{JOBID=~\"$jobid\"}) by (REMOTE_PATH)",
     "legendFormat": "{{REMOTE_PATH}} - Flush"
    },
    {
     "expr": "sum(vnfs_FSYNC_COUNT{JOBID=~\"$jobid\"}) by (REMOTE_PATH)",
     "legendFormat": "{{REMOTE_PATH}} - Fsync"
    },
    {
     "expr": "sum(vnfs_LOCK_COUNT{JOBID=~\"$jobid\"}) by (REMOTE_PATH)",
     "legendFormat": "{{REMOTE_PATH}} - Lock"
    },
    {
     "expr": "sum(vnfs_MMAP_COUNT{JOBID=~\"$jobid\"}) by (REMOTE_PATH)",
     "legendFormat": "{{REMOTE_PATH}} - Mmap"
    }
   ]
  },
  { "title": "Per Client Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Read BW per Client",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(vnfs_READ_BYTES{JOBID=~\"$jobid\"}) by(HOSTNAME) / sum(vnfs_READ_DURATION{JOBID=~\"$jobid\"}) by(HOSTNAME)",
     "legendFormat": "{{JOBID}}, {{HOSTNAME}}"
    }
   ]
  },
  {
   "title": "Write BW per Client",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(vnfs_WRITE_BYTES{JOBID=~\"$jobid\"}) by(HOSTNAME) / sum(vnfs_WRITE_DURATION{JOBID=~\"$jobid\"}) by(HOSTNAME)",
     "legendFormat": "{{JOBID}}, {{HOSTNAME}}"
    }
   ]
  },
  {
   "title": "READ  OPS per Client",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "sum(vnfs_READ_COUNT{JOBID=~\"$jobid\"}) by (HOSTNAME)",
     "legendFormat": "{{JOBID}}, {{HOSTNAME}}"
    }
   ]
  },
  {
   "title": "WRITE OPS per Client",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "expr": "sum(vnfs_WRITE_COUNT{JOBID=~\"$jobid\"}) by (HOSTNAME)",
     "legendFormat": "{{JOBID}}, {{HOSTNAME}}"
    }
   ]
  },
  {
   "title": "Read Metadata OPS per Client",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "sum(vnfs_GETATTR_COUNT{JOBID=~\"$jobid\"} + vnfs_READDIR_COUNT{JOBID=~\"$jobid\"} + vnfs_LOOKUP_COUNT{JOBID=~\"$jobid\"} + vnfs_ACCESS_COUNT{JOBID=~\"$jobid\"} + vnfs_LISTXATTR_COUNT{JOBID=~\"$jobid\"} + vnfs_MMAP_COUNT{JOBID=~\"$jobid\"}) by (HOSTNAME)",
     "legendFormat": "{{JOBID}}, {{HOSTNAME}}"
    }
   ]
  },
  {
   "title": "Write Metadata OPS per Client",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "targets": [
    {
     "expr": "sum(vnfs_OPEN_COUNT{JOBID=~\"$jobid\"} + vnfs_CLOSE_COUNT{JOBID=~\"$jobid\"} + vnfs_SETATTR_COUNT{JOBID=~\"$jobid\"} + vnfs_CREATE_COUNT{JOBID=~\"$jobid\"} + vnfs_LINK_COUNT{JOBID=~\"$jobid\"} + vnfs_UNLINK_COUNT{JOBID=~\"$jobid\"} + vnfs_SYMLINK_COUNT{JOBID=~\"$jobid\"} + vnfs_RENAME_COUNT{JOBID=~\"$jobid\"} + vnfs_MKDIR_COUNT{JOBID=~\"$jobid\"} + vnfs_RMDIR_COUNT{JOBID=~\"$jobid\"} + vnfs_FLUSH_COUNT{JOBID=~\"$jobid\"} + vnfs_FSYNC_COUNT{JOBID=~\"$jobid\"} + vnfs_LOCK_COUNT{JOBID=~\"$jobid\"} + vnfs_MMAP_COUNT{JOBID=~\"$jobid\"}) by (HOSTNAME)",
     "legendFormat": "{{JOBID}}, {{HOSTNAME}}"
    }
   ]
  },
  {
   "title": "Metadata OPS Distribution per Client",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "sum(vnfs_OPEN_COUNT{JOBID=~\"$jobid\"}) by (HOSTNAME)",
     "legendFormat": "{{HOSTNAME}} - Open"
    },
    {
     "expr": "sum(vnfs_CLOSE_COUNT{JOBID=~\"$jobid\"}) by (HOSTNAME)",
     "legendFormat": "{{HOSTNAME}} - Close"
    },
    {
     "expr": "sum(vnfs_GETATTR_COUNT{JOBID=~\"$jobid\"}) by (HOSTNAME)",
     "legendFormat": "{{HOSTNAME}} - Getattr"
    },
    {
     "expr": "sum(vnfs_SETATTR_COUNT{JOBID=~\"$jobid\"}) by (HOSTNAME)",
     "legendFormat": "{{HOSTNAME}} - Setattr"
    },
    {
     "expr": "sum(vnfs_READDIR_COUNT{JOBID=~\"$jobid\"}) by (HOSTNAME)",
     "legendFormat": "{{HOSTNAME}} - Readdir"
    },
    {
     "expr": "sum(vnfs_CREATE_COUNT{JOBID=~\"$jobid\"}) by (HOSTNAME)",
     "legendFormat": "{{HOSTNAME}} - Create"
    },
    {
     "expr": "sum(vnfs_LINK_COUNT{JOBID=~\"$jobid\"}) by (HOSTNAME)",
     "legendFormat": "{{HOSTNAME}} - Link"
    },
    {
     "expr": "sum(vnfs_UNLINK_COUNT{JOBID=~\"$jobid\"}) by (HOSTNAME)",
     "legendFormat": "{{HOSTNAME}} - Unlink"
    },
    {
     "expr": "sum(vnfs_SYMLINK_COUNT{JOBID=~\"$jobid\"}) by (HOSTNAME)",
     "legendFormat": "{{HOSTNAME}} - Symlink"
    },
    {
     "expr": "sum(vnfs_LOOKUP_COUNT{JOBID=~\"$jobid\"}) by (HOSTNAME)",
     "legendFormat": "{{HOSTNAME}} - Lookup"
    },
    {
     "expr": "sum(vnfs_RENAME_COUNT{JOBID=~\"$jobid\"}) by (HOSTNAME)",
     "legendFormat": "{{HOSTNAME}} - Rename"
    },
    {
     "expr": "sum(vnfs_ACCESS_COUNT{JOBID=~\"$jobid\"}) by (HOSTNAME)",
     "legendFormat": "{{HOSTNAME}} - Access"
    },
    {
     "expr": "sum(vnfs_LISTXATTR_COUNT{JOBID=~\"$jobid\"}) by (HOSTNAME)",
     "legendFormat": "{{HOSTNAME}} - Listxattr"
    },
    {
     "expr": "sum(vnfs_MKDIR_COUNT{JOBID=~\"$jobid\"}) by (HOSTNAME)",
     "legendFormat": "{{HOSTNAME}} - Mkdir"
    },
    {
     "expr": "sum(vnfs_RMDIR_COUNT{JOBID=~\"$jobid\"}) by (HOSTNAME)",
     "legendFormat": "{{HOSTNAME}} - Rmdir"
    },
    {
     "expr": "sum(vnfs_FLUSH_COUNT{JOBID=~\"$jobid\"}) by (HOSTNAME)",
     "legendFormat": "{{HOSTNAME}} - Flush"
    },
    {
     "expr": "sum(vnfs_FSYNC_COUNT{JOBID=~\"$jobid\"}) by (HOSTNAME)",
     "legendFormat": "{{HOSTNAME}} - Fsync"
    },
    {
     "expr": "sum(vnfs_LOCK_COUNT{JOBID=~\"$jobid\"}) by (HOSTNAME)",
     "legendFormat": "{{HOSTNAME}} - Lock"
    },
    {
     "expr": "sum(vnfs_MMAP_COUNT{JOBID=~\"$jobid\"}) by (HOSTNAME)",
     "legendFormat": "{{HOSTNAME}} - Mmap"
    }
   ]
  },
  { "title": "Per UID Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "Read BW per UID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(vnfs_READ_BYTES{JOBID=~\"$jobid\"}) by(UID) / sum(vnfs_READ_DURATION{JOBID=~\"$jobid\"}) by(UID)",
     "legendFormat": "{{JOBID}}, {{UID}}"
    }
   ]
  },
  {
   "title": "Write BW per UID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(vnfs_WRITE_BYTES{JOBID=~\"$jobid\"}) by(UID) / sum(vnfs_WRITE_DURATION{JOBID=~\"$jobid\"}) by(UID)",
     "legendFormat": "{{JOBID}}, {{UID}}"
    }
   ]
  },
  {
   "title": "READ OPS per UID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "targets": [
    {
     "expr": "sum(vnfs_READ_COUNT{JOBID=~\"$jobid\"}) by (UID)",
     "legendFormat": "{{JOBID}}, {{UID}}"
    }
   ]
  },
  {
   "title": "WRITE OPS per UID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "targets": [
    {
     "expr": "sum(vnfs_WRITE_COUNT{JOBID=~\"$jobid\"}) by (UID)",
     "legendFormat": "{{JOBID}}, {{UID}}"
    }
   ]
  },
  {
   "title": "Read Metadata OPS per UID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "targets": [
    {
     "expr": "sum(vnfs_GETATTR_COUNT{JOBID=~\"$jobid\"} + vnfs_READDIR_COUNT{JOBID=~\"$jobid\"} + vnfs_LOOKUP_COUNT{JOBID=~\"$jobid\"} + vnfs_ACCESS_COUNT{JOBID=~\"$jobid\"} + vnfs_LISTXATTR_COUNT{JOBID=~\"$jobid\"} + vnfs_MMAP_COUNT{JOBID=~\"$jobid\"}) by (UID)",
     "legendFormat": "{{JOBID}}, {{UID}}"
    }
   ]
  },
  {
   "title": "Write Metadata OPS per UID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
   "targets": [
    {
     "expr": "sum(vnfs_OPEN_COUNT{JOBID=~\"$jobid\"} + vnfs_CLOSE_COUNT{JOBID=~\"$jobid\"} + vnfs_SETATTR_COUNT{JOBID=~\"$jobid\"} + vnfs_CREATE_COUNT{JOBID=~\"$jobid\"} + vnfs_LINK_COUNT{JOBID=~\"$jobid\"} + vnfs_UNLINK_COUNT{JOBID=~\"$jobid\"} + vnfs_SYMLINK_COUNT{JOBID=~\"$jobid\"} + vnfs_RENAME_COUNT{JOBID=~\"$jobid\"} + vnfs_MKDIR_COUNT{JOBID=~\"$jobid\"} + vnfs_RMDIR_COUNT{JOBID=~\"$jobid\"} + vnfs_FLUSH_COUNT{JOBID=~\"$jobid\"} + vnfs_FSYNC_COUNT{JOBID=~\"$jobid\"} + vnfs_LOCK_COUNT{JOBID=~\"$jobid\"} + vnfs_MMAP_COUNT{JOBID=~\"$jobid\"}) by (UID)",
     "legendFormat": "{{JOBID}}, {{UID}}"
    }
   ]
  },
  {
   "title": "Metadata OPS Distribution per UID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 133 },
   "targets": [
    {
     "expr": "sum(vnfs_OPEN_COUNT{JOBID=~\"$jobid\"}) by (UID)",
     "legendFormat": "{{UID}} - Open"
    },
    {
     "expr": "sum(vnfs_CLOSE_COUNT{JOBID=~\"$jobid\"}) by (UID)",
     "legendFormat": "{{UID}} - Close"
    },
    {
     "expr": "sum(vnfs_GETATTR_COUNT{JOBID=~\"$jobid\"}) by (UID)",
     "legendFormat": "{{UID}} - Getattr"
    },
    {
     "expr": "sum(vnfs_SETATTR_COUNT{JOBID=~\"$jobid\"}) by (UID)",
     "legendFormat": "{{UID}} - Setattr"
    },
    {
     "expr": "sum(vnfs_READDIR_COUNT{JOBID=~\"$jobid\"}) by (UID)",
     "legendFormat": "{{UID}} - Readdir"
    },
    {
     "expr": "sum(vnfs_CREATE_COUNT{JOBID=~\"$jobid\"}) by (UID)",
     "legendFormat": "{{UID}} - Create"
    },
    {
     "expr": "sum(vnfs_LINK_COUNT{JOBID=~\"$jobid\"}) by (UID)",
     "legendFormat": "{{UID}} - Link"
    },
    {
     "expr": "sum(vnfs_UNLINK_COUNT{JOBID=~\"$jobid\"}) by (UID)",
     "legendFormat": "{{UID}} - Unlink"
    },
    {
     "expr": "sum(vnfs_SYMLINK_COUNT{JOBID=~\"$jobid\"}) by (UID)",
     "legendFormat": "{{UID}} - Symlink"
    },
    {
     "expr": "sum(vnfs_LOOKUP_COUNT{JOBID=~\"$jobid\"}) by (UID)",
     "legendFormat": "{{UID}} - Lookup"
    },
    {
     "expr": "sum(vnfs_RENAME_COUNT{JOBID=~\"$jobid\"}) by (UID)",
     "legendFormat": "{{UID}} - Rename"
    },
    {
     "expr": "sum(vnfs_ACCESS_COUNT{JOBID=~\"$jobid\"}) by (UID)",
     "legendFormat": "{{UID}} - Access"
    },
    {
     "expr": "sum(vnfs_LISTXATTR_COUNT{JOBID=~\"$jobid\"}) by (UID)",
     "legendFormat": "{{UID}} - Listxattr"
    },
    {
     "expr": "sum(vnfs_MKDIR_COUNT{JOBID=~\"$jobid\"}) by (UID)",
     "legendFormat": "{{UID}} - Mkdir"
    },
    {
     "expr": "sum(vnfs_RMDIR_COUNT{JOBID=~\"$jobid\"}) by (UID)",
     "legendFormat": "{{UID}} - Rmdir"
    },
    {
     "expr": "sum(vnfs_FLUSH_COUNT{JOBID=~\"$jobid\"}) by (UID)",
     "legendFormat": "{{UID}} - Flush"
    },
    {
     "expr": "sum(vnfs_FSYNC_COUNT{JOBID=~\"$jobid\"}) by (UID)",
     "legendFormat": "{{UID}} - Fsync"
    },
    {
     "expr": "sum(vnfs_LOCK_COUNT{JOBID=~\"$jobid\"}) by (UID)",
     "legendFormat": "{{UID}} - Lock"
    },
    {
     "expr": "sum(vnfs_MMAP_COUNT{JOBID=~\"$jobid\"}) by (UID)",
     "legendFormat": "{{UID}} - Mmap"
    }
   ]
  }
 ]
}